### ISSUE TITLE
CMake build giving invalid output or seg fault on some inputs using Z_FIXED

### ISSUE THREAD

**Issue by chanphil** [madler/zlib#485]
The issue seems like it may depend on the system configuration, so I've including a minimalistic Dockerfile to create a clean test environment to demonstrate the issue.  The Dockerfile is included in [zlib_test.tar.gz](https://github.com/madler/zlib/files/4495077/zlib_test.tar.gz), along with input data the hits the issue (test_data), a simple python program to run the input through zlib (test.py) and a shell script (run_test.sh) to demonstrate some of the strange behaviour I've observed.  [log.txt](https://github.com/madler/zlib/files/4495076/log.txt) shows a run through this demonstration (the most interesting bits are at the bottom, the rest is mostly building up the docker container to run the tests).

To summarize my testing and observations:
- I'm using the develop branch, but I've observed the issue on master as well.
- The particular input data provided here exhibits two different failure modes depending on the compression level (crc  error or seg fault).  I have other failing inputs, and they all give some variation of an error indicating invalid input (not necessarily a crc error) when attempting to decompress the output from zlib, or a seg fault.
- This issue appears to only occur when installing zlib using CMake.  Using the configure script works fine with the test cases I have.
- This issue appears to only occur when compressing using the Z_FIXED strategy.
- As demonstrated in run_tests.sh, installing libpython3.6 via apt-get in the docker makes the issue go away, but it doesn't come back if libpython3.6 is purged via apt-get.
- Despite what the above point would imply, the issue is not python specific.  I've observed it while using zlib via C/C++ code, but that code was too deeply embedded into other code to easily pull out for a simple example.  The libpython3.6 install makes the issue go away for the C/C++ code as well.

**Comment by dankegel** [comment]
FWIW, the python crash is not inside zlib itself, it seems:
```
#0  0x0000000000591d0e in _PyBytes_Resize () at ../Objects/bytesobject.c:2995
#1  0x00000000005b7863 in arrange_output_buffer_with_maximum (zst=<optimized out>, zst=<optimized out>, max_length=9223372036854775807, 
    length=<optimized out>, buffer=0x7fffffffde88) at ../Modules/zlibmodule.c:174
#2  arrange_output_buffer () at ../Modules/zlibmodule.c:191
#3  0x00000000005b82b1 in zlib_Compress_compress_impl (data=<optimized out>, data=<optimized out>, self=0x7ffff6a88810)
    at ../Modules/zlibmodule.c:674
#4  zlib_Compress_compress () at ../Modules/clinic/zlibmodule.c.h:221
```

**Comment by dankegel** [comment]
Fun facts:
1) the test program fails even if you don't install your own zlib?  Try skipping zlib build in your Dockerfile.
2) the container ships libpython3.x-minimal; libpython3.x itself mostly just adds libpython3.x.so
3) PyInit_zlib is built into both /usr/bin/python3 and libpython3.x.so, which, uh, is confusing
4) The cmake build doesn't generate bit-for-bit identical installed shared libraries, but even if you fix that, the problem seems to remain

Seems like Python is complicating the picture significantly.
Extracting a test case from C/C++ code might be hard, but you could try porting your
build system to meson or cmake, doing a unity build, and bisecting with c-reduce :-)
